################################################################################
# \file bsp.mk
#
# \brief
# Define the BSP for the KIT_PSOCE84_EVK
#
################################################################################
# \copyright
# Copyright 2021-2024 Cypress Semiconductor Corporation (an Infineon company) or
# an affiliate of Cypress Semiconductor Corporation
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

ifeq ($(WHICHFILE),true)
$(info Processing $(lastword $(MAKEFILE_LIST)))
endif

# Any additional components to apply when using this board.
# Use a default CM0+ image (CM0P_SLEEP). This can be swapped for a different
# pre-built image or removed if custom built project.
BSP_COMPONENTS:=HCI-UART WIFI_INTERFACE_SDIO SM CYW55513IUBG wlbga_iPA_sLNA_ANT0_LHL_XTAL_IN

# Any additional defines to apply when using this board.
BSP_DEFINES:=CY_USING_HAL
BSP_DEFINES+=CY_WIFI_COUNTRY='WHD_COUNTRY_UNITED_STATES'
BSP_DEFINES+=CYBSP_WIFI_WL_HOSTWAKE_DRIVE_MODE=CYHAL_GPIO_DRIVE_OPENDRAINDRIVESLOW
BSP_DEFINES+=CYBSP_WIFI_WL_HOSTWAKE_INIT_STATE=WHD_TRUE

# Path to the flash loaders to patch for this board
CY_QSPI_FLM_DIR?=$(MTB_TOOLS__TARGET_DIR)/config/FlashLoaders/

# Path to the patched flash loaders for this board
CY_QSPI_FLM_DIR_OUTPUT?=$(MTB_TOOLS__TARGET_DIR)/config/GeneratedSource/

APPTYPE?=flash
VCORE_ATTRS?=NON_SECURE
CORE?=CM33
SEC_API_LINK_FILE_NAME=sec_api_link.o

ifeq ($(TOOLCHAIN),GCC_ARM)
# To pick up pse84_common.ld
LDFLAGS += -Xlinker -L $(MTB_TOOLS__TARGET_DIR)/COMPONENT_CM33/TOOLCHAIN_$(TOOLCHAIN)
else ifeq ($(TOOLCHAIN),ARM)
LDFLAGS += --undefined=__scatterload_copy
endif

# Specify the path to the linker script to use
ifeq ($(TOOLCHAIN),GCC_ARM)
    BSP_LINKER_SCRIPT_EXT:=ld
else ifeq ($(TOOLCHAIN),ARM)
    BSP_LINKER_SCRIPT_EXT:=sct
else ifeq ($(TOOLCHAIN),IAR)
    BSP_LINKER_SCRIPT_EXT:=icf
endif


ifeq ($(VCORE_ATTRS),NON_SECURE)

ifeq ($(APPTYPE), ram)
MTB_BSP__LINKER_SCRIPT:=$(MTB_TOOLS__TARGET_DIR)/COMPONENT_$(CORE)/TOOLCHAIN_$(TOOLCHAIN)/pse84_ns_ram.$(BSP_LINKER_SCRIPT_EXT)
else
MTB_BSP__LINKER_SCRIPT:=$(MTB_TOOLS__TARGET_DIR)/COMPONENT_$(CORE)/TOOLCHAIN_$(TOOLCHAIN)/linker.$(BSP_LINKER_SCRIPT_EXT)
endif

COMPONENTS+=NON_SECURE_DEVICE

ifeq ($(CORE), CM33)
LDLIBS+=$(MTB_TOOLS__TARGET_DIR)/COMPONENT_$(CORE)/TOOLCHAIN_$(TOOLCHAIN)/COMPONENT_PREBUILT_SECURE_APP/$(SEC_API_LINK_FILE_NAME)
endif

else
MTB_BSP__LINKER_SCRIPT:=$(MTB_TOOLS__TARGET_DIR)/COMPONENT_$(CORE)/TOOLCHAIN_$(TOOLCHAIN)/pse84_s_$(APPTYPE).$(BSP_LINKER_SCRIPT_EXT)
COMPONENTS+=SECURE_DRIVERS SECURE_DEVICE
endif

#Generate binary image
ifeq ($(TOOLCHAIN),ARM)
CY_BSP_POSTBUILD+=$(MTB_TOOLCHAIN_ARM__BASE_DIR)/bin/fromelf --output=$(MTB_TOOLS__OUTPUT_CONFIG_DIR)/$(APPNAME).bin --bincombined $(MTB_TOOLS__OUTPUT_CONFIG_DIR)/$(APPNAME).$(MTB_RECIPE__SUFFIX_TARGET);
else
CY_BSP_POSTBUILD+=$(MTB_TOOLCHAIN_GCC_ARM__BASE_DIR)/bin/arm-none-eabi-objcopy -O binary $(MTB_TOOLS__OUTPUT_CONFIG_DIR)/$(APPNAME).$(MTB_RECIPE__SUFFIX_TARGET) $(MTB_TOOLS__OUTPUT_CONFIG_DIR)/$(APPNAME).bin;
endif

#Work around for H1 Hosted mode
DISABLE_COMPONENTS+=CAT5

################################################################################
# ALL ITEMS BELOW THIS POINT ARE AUTO GENERATED BY THE BSP ASSISTANT TOOL.
# DO NOT MODIFY DIRECTLY. CHANGES SHOULD BE MADE THROUGH THE BSP ASSISTANT.
################################################################################

# Board device selection. MPN_LIST tracks what was selected in the BSP Assistant
# All other variables are derived by BSP Assistant based on the MPN_LIST.
MPN_LIST:=PSE846GPS2DBZC4 CYW55513IUBG
DEVICE:=PSE846GPS2DBZC4
ADDITIONAL_DEVICES:=CYW55513IUBG
DEVICE_COMPONENTS:=55500 55500A1 CAT1 CAT1D PSE84_A0
DEVICE_CYW55513IUBG_CORES:=CORE_NAME_CM33_0
DEVICE_CYW55513IUBG_DIE:=55500A1
DEVICE_CYW55513IUBG_FLASH_KB:=0
DEVICE_CYW55513IUBG_SRAM_KB:=768
DEVICE_DEFINES:=BLHS_SUPPORT TRXV5
DEVICE_LIST:=PSE846GPS2DBZC4 CYW55513IUBG
DEVICE_PSE846GPS2DBZC4_CORES:=CORE_NAME_CM33_0 CORE_NAME_CM55_0
DEVICE_PSE846GPS2DBZC4_DIE:=EXPLORER_A0
DEVICE_PSE846GPS2DBZC4_FEATURES:=CM33_0_CMSE_PRESENT CM33_0_DSP_PRESENT CM33_0_FPU_PRESENT CM55_0_DSP_PRESENT CM55_0_FPU_PRESENT CM55_0_MVE_PRESENT EPC2
DEVICE_PSE846GPS2DBZC4_FLASH_KB:=0
DEVICE_PSE846GPS2DBZC4_SRAM_KB:=1024
DEVICE_TOOL_IDS:=audio-fe-configurator bsp-assistant bt-configurator device-configurator dfuh-tool edge-protect-configurator library-manager ml-configurator project-creator qspi-configurator smartio-configurator
RECIPE_DIR:=$(SEARCH_recipe-make-cat1d)

DEVICE_PSE846GPS2DBZC4_FEATURES+=CM33_0_DSP_PRESENT CM33_0_FPU_PRESENT CM55_0_FPU_PRESENT CM55_0_MVE_PRESENT
